<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_AssignToName</name>
   <tag></tag>
   <elementGuidId>5b5bd2df-807d-4bf0-b186-fd856ab6063f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ireq-assign-request-view/div/dew-row/dew-col/dew-col[2]/dew-text</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
