<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WorkFlow_Field</name>
   <tag></tag>
   <elementGuidId>c6bc2847-eefb-4898-a4c5-15b695660a7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dew-scroll-section[@id='4']/dew-container/dew-paper/dew-section/dew-flex/dew-flex-item[1]/h5</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
