<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Error2</name>
   <tag></tag>
   <elementGuidId>539d3416-404e-4d4e-a310-ea34b0b6209f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>html/body/dew-app-root/div/div[2]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
