<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Backnavg_icon</name>
   <tag></tag>
   <elementGuidId>352f7538-d1af-4b4b-b88c-32edf62b6dbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/dew-block/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/dew-block/div/i</value>
   </webElementProperties>
</WebElementEntity>
