<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_loadmore(Audit)</name>
   <tag></tag>
   <elementGuidId>d31ec85f-131f-4482-94ee-82f8ada41ce6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//dew-block/ireq-audit/div[2]/dew-btn/button</value>
   </webElementProperties>
</WebElementEntity>
