<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_delete</name>
   <tag></tag>
   <elementGuidId>724eed30-767a-4f3e-8a9a-2d8d708fe328</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//*[@id='1']/dew-container/dew-paper/dew-section/dew-block/dew-request-basic-details/div/dew-row[4]/dew-col/div/div[2]/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
