<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Reqnumber_field</name>
   <tag></tag>
   <elementGuidId>1d7be33e-3b17-49e0-aeca-70a1fa227073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//*[@id='1']/dew-container/dew-paper/dew-section/dew-block/dew-request-basic-details/div/dew-row[1]/dew-col[1]/div/span[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
