<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GhostUserID</name>
   <tag></tag>
   <elementGuidId>71ed1c23-b85b-480e-8a0f-e62bc6d54e68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='pnl_loginForm']/form/fieldset[3]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='pnl_loginForm']/form/fieldset[3]/div[1]/input</value>
   </webElementProperties>
</WebElementEntity>
