<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GhoshPassword</name>
   <tag></tag>
   <elementGuidId>0a30f6af-3808-40e2-9820-e60edebf0b71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='pnl_loginForm']/form/fieldset[4]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
