<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProcurementServicesList</name>
   <tag></tag>
   <elementGuidId>ff5d1a6c-d651-4c82-b9c9-314e841f29ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='main']/irequest-home/div[3]/div/dew-section/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='main']/irequest-home/div[3]/div/dew-section/div</value>
   </webElementProperties>
</WebElementEntity>
