<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_updatedondate</name>
   <tag></tag>
   <elementGuidId>33007744-aea6-4295-b6da-77c88714aaab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/dew-tab/div[2]/div[1]/dew-service-request-card/div/div[2]/dew-row/dew-col[3]/p[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
