<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Number of service requests</name>
   <tag></tag>
   <elementGuidId>81e14aaf-f79a-43e3-9ae3-c4661b41328e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='clearfix']/div/dew-tab/dew-block/dew-row/dew-col/p/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='clearfix']/div/dew-tab/dew-block/dew-row/dew-col/p/span</value>
   </webElementProperties>
</WebElementEntity>
