<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox1</name>
   <tag></tag>
   <elementGuidId>28b2e314-2c1a-4d5c-8f3c-e3f397920470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='df_dfSection_DFSECTION_13_3_2018_17_48_26_726_pg27kl8sb']/div[2]/ul/li[5]/div/label[1]/input</value>
   </webElementProperties>
</WebElementEntity>
