<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date-time_field</name>
   <tag></tag>
   <elementGuidId>ed790b6f-cc1e-4b57-a350-e16497545221</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='df_dfDT_19_4_2018_16_3_6_725_ek021kbhs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='df_dfDT_19_4_2018_16_3_6_725_ek021kbhs']</value>
   </webElementProperties>
</WebElementEntity>
