<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date-time_field</name>
   <tag></tag>
   <elementGuidId>ed790b6f-cc1e-4b57-a350-e16497545221</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='df_dfDT_13_3_2018_19_27_17_501_ant4kqbp8']</value>
   </webElementProperties>
</WebElementEntity>
