<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Day_selecter</name>
   <tag></tag>
   <elementGuidId>d2668f1b-4c93-4652-8408-cf6bfd0f55e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='zydf-ui-datepicker-div']/table/tbody/tr[4]/td[3]/a</value>
   </webElementProperties>
</WebElementEntity>
