<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown1</name>
   <tag></tag>
   <elementGuidId>cd3c832a-0c5d-4188-8876-9d90cfae5f1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='df_dfDD_13_3_2018_19_19_2_758_egurr1adm_dd']</value>
   </webElementProperties>
</WebElementEntity>
