<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown2</name>
   <tag></tag>
   <elementGuidId>368956c9-84f5-4882-bb1e-dead4a2e9736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='df_dfMS_13_3_2018_19_21_6_229_9zk87v9tx_ms']</value>
   </webElementProperties>
</WebElementEntity>
