<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Flexisave_table</name>
   <tag></tag>
   <elementGuidId>0ab524ef-52ff-4d78-8d5a-b4b44f80ca44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='colcTblId_20_3_2018_13_51_18_410_hs8hllc2g_wrapper']/div[3]/div[3]/div[2]/div/table/tbody/tr/td/div/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
