<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Month_field</name>
   <tag></tag>
   <elementGuidId>3ee61937-ffdf-45b6-bd77-154f30c46bdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@class=&quot;ui-datepicker-month&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@class=&quot;ui-datepicker-month&quot;]</value>
   </webElementProperties>
</WebElementEntity>
