<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Numeric_field</name>
   <tag></tag>
   <elementGuidId>65124d5b-063c-4b91-8924-82a7f3114757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='df_dfNM_13_3_2018_18_1_48_831_kxr8h4p49']</value>
   </webElementProperties>
</WebElementEntity>
