<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textarea_field</name>
   <tag></tag>
   <elementGuidId>3b36c8dd-d4e2-447f-9258-300ccaec83c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='df_dfTF_13_3_2018_17_53_24_599_p3giwn432']</value>
   </webElementProperties>
</WebElementEntity>
