<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MessageType</name>
   <tag></tag>
   <elementGuidId>814809b6-6a89-4eba-8566-7188af823d30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='modal-body']/dew-modal-body/dew-row[1]/dew-col[2]/div/irequest-dropdown/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='modal-body']/dew-modal-body/dew-row[1]/dew-col[2]/div/irequest-dropdown/div</value>
   </webElementProperties>
</WebElementEntity>
