<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MessageTypeLbl</name>
   <tag></tag>
   <elementGuidId>040a5f8f-620f-49cb-b0bf-9e14140578c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='modal-body']/dew-modal-body/dew-row[1]/dew-col[2]/div/label</value>
   </webElementProperties>
</WebElementEntity>
