<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PriorityLbl</name>
   <tag></tag>
   <elementGuidId>e2b7e6c0-f7f6-48bb-a6bf-3e40fd9e5c63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='modal-body']/dew-modal-body/dew-row[1]/dew-col[3]/div/label</value>
   </webElementProperties>
</WebElementEntity>
