<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SummaryLbl</name>
   <tag></tag>
   <elementGuidId>3af4f94e-e41c-43f8-a73b-125bd1516848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='modal-body']/dew-modal-body/dew-row[2]/dew-col[1]/div/label</value>
   </webElementProperties>
</WebElementEntity>
