<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HOME</name>
   <tag></tag>
   <elementGuidId>77dd24b2-3f45-47de-babd-e40c40101d55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//dew-col[@class='col-8']/dew-flex/dew-flex-item[1]/div/a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//dew-col[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//dew-col[@class='col-8']/dew-flex/dew-flex-item[1]/div/a</value>
   </webElementProperties>
</WebElementEntity>
