<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ReportAnIssue</name>
   <tag></tag>
   <elementGuidId>fa39be32-84ff-43f8-8390-776044807f27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//dew-col[@class='col-8']/dew-flex/dew-flex-item[4]/div/div/a[3]</value>
   </webElementProperties>
</WebElementEntity>
