<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Card_requesttype</name>
   <tag></tag>
   <elementGuidId>d14de6b4-1da6-46b9-a634-caa1b640e611</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/dew-tab/div/dew-block/dew-approvals-card[1]/dew-card/dew-card-body/dew-row/dew-col[2]/p[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
