<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Card_requestname</name>
   <tag></tag>
   <elementGuidId>c877257f-f0fb-4d06-ab58-28a4fcb92671</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/dew-tab/div/dew-block/dew-approvals-card[1]/dew-card/dew-card-header/dew-row/dew-col[2]/span[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
