<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Card_updatedondate</name>
   <tag></tag>
   <elementGuidId>b8e8d588-0b9d-4ebe-b603-b9147594836e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/dew-tab/div/dew-block/dew-approvals-card[1]/dew-card/dew-card-body/dew-row/dew-col[3]/p[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
