<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_BackNavigation</name>
   <tag></tag>
   <elementGuidId>ddc5d68b-bae3-4f0c-982d-02b6816a0e2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dew-irequest-layout/dew-block/dew-todo/div/dew-flex/dew-flex-item/h3/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
