<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_ApproveCard1</name>
   <tag></tag>
   <elementGuidId>cc6fcab6-94fb-403e-8ff4-cf1367abb7c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dew-approvals-card[1]/dew-paper/div/div[2]/dew-row/dew-col[4]/div/a[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
