<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Rejectcard1</name>
   <tag></tag>
   <elementGuidId>196afa7a-4a38-4d5f-94a1-5a67763d3c4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dew-block/dew-approvals-card[1]/dew-paper/div/div[2]/dew-row/dew-col[4]/div/a[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
