<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Overviewelmt_prst</name>
   <tag></tag>
   <elementGuidId>fca934bd-0508-477b-b029-d8866446d123</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>html/body/dew-app-root/dew-irequest-layout/dew-block/dew-irequest/dew-section[1]/dew-flex/dew-flex-item[1]/h5</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
