<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Page_title</name>
   <tag></tag>
   <elementGuidId>9b8d6213-ceae-4f86-ac25-ac472b0dd219</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>html/body/dew-app-root/dew-irequest-layout/dew-block/ng-component/div/dew-flex/dew-flex-item[1]/h3</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
