<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Request_nameLPG</name>
   <tag></tag>
   <elementGuidId>fadd6eb7-8d80-4afc-b1f3-e56920927d99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dew-approvals-card[1]/dew-card/dew-card-header/dew-row/dew-col[2]/span[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
