<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtarea_ApprovalComment</name>
   <tag></tag>
   <elementGuidId>8138fc1d-b821-4089-80ca-ef17275c83b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//dew-block/dew-approvals-card[1]/dew-paper/div/div[2]/dew-modal[2]/div/div/div[2]/dew-modal-body/div/textarea</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
