<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field_requesttype</name>
   <tag></tag>
   <elementGuidId>adfa2788-60e6-466b-9fca-aed5d6eb032a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/irequest-new-request/div[2]/form/dew-block[1]/irequest-new-basic-details/div/dew-row[1]/dew-col[2]/span[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
