<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ManagerEmailID</name>
   <tag></tag>
   <elementGuidId>e4da0e37-add0-4fe4-8881-b4f6a9a0854b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='userProfileCnt']/table[1]/tbody/tr[7]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
