<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProfileImage</name>
   <tag></tag>
   <elementGuidId>a6dd9317-c8da-4947-83ac-992d42de268c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='userProfileCnt']/table/tbody/tr[4]/td[@class='padUserD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='userProfileCnt']/table/tbody/tr[4]/td[@class='padUserD']</value>
   </webElementProperties>
</WebElementEntity>
